services:
  laravel_app:
    container_name: aeia-app
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      /bin/sh -c "pwd &&
                  php artisan key:generate &&
                  php artisan serve --host=0.0.0.0 --port=8000"
    volumes:
      - .:/app
      - ./vendor:/app/vendor
      - ./storage:/app/storage
    ports:
      - 8000:8000
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: "5432"
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db
    networks:
      - shared_network

  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shared_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    ports:
      - "5050:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - shared_network

  mailhog_server:
    image: mailhog/mailhog
    container_name: cont_mailhog_server
    tty: true
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - shared_network

volumes:
  postgres-data:
  pgadmin:

networks:
  shared_network:
    external: true
    name: shared_network